// Generated by scripts/gen-catalog.ts — do not edit by hand.
export interface CatalogEntry {
  id: string;
  people: 1 | 2;
  line: string;
}

export const CATALOG: CatalogEntry[] = [
  {
    "id": "solo-classic-hip",
    "people": 1,
    "line": "solo-classic-hip | Hand on Hip | solo | standing, full body | scenes: city, landmark, wall, event, park, office | vibes: confident, elegant"
  },
  {
    "id": "solo-both-hips",
    "people": 1,
    "line": "solo-both-hips | Power Stance | solo | standing, full body | scenes: city, mountain, landmark, office, gym | vibes: confident, professional"
  },
  {
    "id": "solo-pockets",
    "people": 1,
    "line": "solo-pockets | Hands in Pockets | solo | standing, full body | scenes: city, cafe, night, wall, park | vibes: casual, confident"
  },
  {
    "id": "solo-cross-legs",
    "people": 1,
    "line": "solo-cross-legs | Crossed Ankles | solo | standing, full body | scenes: city, cafe, wall, landmark, event | vibes: elegant, casual"
  },
  {
    "id": "solo-wall-lean",
    "people": 1,
    "line": "solo-wall-lean | Wall Lean | solo | leaning, full body | scenes: wall, city, night, cafe | vibes: casual, confident | needs a wall or pillar"
  },
  {
    "id": "solo-wall-foot-up",
    "people": 1,
    "line": "solo-wall-foot-up | Foot on the Wall | solo | leaning, full body | scenes: wall, city, night | vibes: casual, confident | needs a wall"
  },
  {
    "id": "solo-arms-crossed",
    "people": 1,
    "line": "solo-arms-crossed | Arms Crossed | solo | standing, half body | scenes: office, city, gym, event | vibes: professional, confident"
  },
  {
    "id": "solo-hair-touch",
    "people": 1,
    "line": "solo-hair-touch | Hand in Hair | solo | standing, half body | scenes: beach, sunset, park, cafe, water | vibes: elegant, candid"
  },
  {
    "id": "solo-thinker",
    "people": 1,
    "line": "solo-thinker | Chin on Hand | solo | standing, half body | scenes: cafe, office, home | vibes: professional, candid"
  },
  {
    "id": "solo-wave",
    "people": 1,
    "line": "solo-wave | Hello Wave | solo | standing, full body | scenes: beach, mountain, landmark, park, snow | vibes: playful, casual"
  },
  {
    "id": "solo-victory-v",
    "people": 1,
    "line": "solo-victory-v | Victory V | solo | standing, full body | scenes: mountain, beach, sunset, landmark, snow | vibes: adventurous, playful"
  },
  {
    "id": "solo-arms-wide",
    "people": 1,
    "line": "solo-arms-wide | Arms Wide Open | solo | standing, full body | scenes: mountain, beach, sunset, water, snow | vibes: adventurous, candid"
  },
  {
    "id": "solo-back-view-arms",
    "people": 1,
    "line": "solo-back-view-arms | Back to Camera | solo | standing, full body | scenes: mountain, beach, sunset, water, landmark | vibes: adventurous, candid"
  },
  {
    "id": "solo-look-back",
    "people": 1,
    "line": "solo-look-back | Over the Shoulder | solo | standing, full body | scenes: city, landmark, beach, sunset, event | vibes: elegant, candid"
  },
  {
    "id": "solo-walk-toward",
    "people": 1,
    "line": "solo-walk-toward | Walking Toward | solo | walking, full body | scenes: city, beach, park, stairs, landmark | vibes: candid, casual"
  },
  {
    "id": "solo-profile",
    "people": 1,
    "line": "solo-profile | Side Profile | solo | standing, half body | scenes: sunset, beach, water, mountain, city | vibes: elegant, candid"
  },
  {
    "id": "solo-head-tilt-smile",
    "people": 1,
    "line": "solo-head-tilt-smile | Head Tilt Smile | solo | standing, half body | scenes: cafe, park, event, home, beach | vibes: casual, playful"
  },
  {
    "id": "solo-hands-behind-head",
    "people": 1,
    "line": "solo-hands-behind-head | Hands Behind Head | solo | standing, half body | scenes: beach, park, mountain, gym | vibes: casual, confident"
  },
  {
    "id": "solo-point-view",
    "people": 1,
    "line": "solo-point-view | Point at the View | solo | standing, full body | scenes: mountain, landmark, city, water | vibes: adventurous, playful"
  },
  {
    "id": "solo-jump",
    "people": 1,
    "line": "solo-jump | Jump Shot | solo | jumping, full body | scenes: beach, mountain, park, snow, sunset | vibes: playful, adventurous"
  },
  {
    "id": "solo-sit-bench",
    "people": 1,
    "line": "solo-sit-bench | Bench Sit | solo | sitting, full body | scenes: park, city, cafe, water, landmark | vibes: casual, candid | needs a bench, ledge or chair"
  },
  {
    "id": "solo-sit-knee-up",
    "people": 1,
    "line": "solo-sit-knee-up | Knee Up Sit | solo | sitting, full body | scenes: stairs, beach, mountain, park, water | vibes: casual, adventurous | needs a step, rock or ledge"
  },
  {
    "id": "solo-sit-stairs",
    "people": 1,
    "line": "solo-sit-stairs | Stair Sit | solo | sitting, full body | scenes: stairs, city, landmark | vibes: casual, confident | needs steps"
  },
  {
    "id": "solo-sit-legs-out",
    "people": 1,
    "line": "solo-sit-legs-out | Beach Lounge | solo | sitting, full body | scenes: beach, park, water, sunset | vibes: casual, candid"
  },
  {
    "id": "solo-crouch",
    "people": 1,
    "line": "solo-crouch | Street Crouch | solo | crouching, full body | scenes: city, night, wall, stairs | vibes: confident, casual"
  },
  {
    "id": "solo-coffee",
    "people": 1,
    "line": "solo-coffee | Coffee Moment | solo | standing, half body | scenes: cafe, home, office | vibes: candid, casual | needs a cup or drink"
  },
  {
    "id": "solo-railing",
    "people": 1,
    "line": "solo-railing | Railing Lean | solo | leaning, half body | scenes: water, city, mountain, landmark, night | vibes: candid, elegant | needs a railing or balcony"
  },
  {
    "id": "solo-jacket-hold",
    "people": 1,
    "line": "solo-jacket-hold | Jacket Over Shoulder | solo | standing, full body | scenes: city, event, night, office | vibes: confident, elegant"
  },
  {
    "id": "solo-stairs-walk",
    "people": 1,
    "line": "solo-stairs-walk | Stair Climb | solo | walking, full body | scenes: stairs, landmark, city | vibes: candid, elegant | needs steps"
  },
  {
    "id": "solo-gym-flex",
    "people": 1,
    "line": "solo-gym-flex | Flex | solo | standing, half body | scenes: gym, beach | vibes: confident, playful"
  },
  {
    "id": "solo-snow-sky",
    "people": 1,
    "line": "solo-snow-sky | Reach for the Sky | solo | standing, full body | scenes: snow, mountain, beach, park | vibes: playful, adventurous"
  },
  {
    "id": "solo-portrait-straight",
    "people": 1,
    "line": "solo-portrait-straight | Classic Portrait | solo | standing, half body | scenes: office, event, home, park, city | vibes: professional, elegant"
  },
  {
    "id": "solo-landmark-small",
    "people": 1,
    "line": "solo-landmark-small | Tiny in the View | solo | standing, full body | scenes: mountain, landmark, water, snow, beach | vibes: adventurous, candid"
  },
  {
    "id": "duo-hold-hands",
    "people": 2,
    "line": "duo-hold-hands | Hand in Hand | couple | standing, full body | scenes: beach, park, city, sunset, landmark, event | vibes: romantic, casual"
  },
  {
    "id": "duo-side-hug",
    "people": 2,
    "line": "duo-side-hug | Side Hug | couple | standing, full body | scenes: landmark, mountain, event, city, park, beach | vibes: casual, romantic"
  },
  {
    "id": "duo-back-to-back",
    "people": 2,
    "line": "duo-back-to-back | Back to Back | couple | standing, full body | scenes: city, wall, park, event, gym | vibes: confident, playful"
  },
  {
    "id": "duo-forehead-touch",
    "people": 2,
    "line": "duo-forehead-touch | Forehead Touch | couple | standing, half body | scenes: sunset, beach, park, event, water | vibes: romantic, elegant"
  },
  {
    "id": "duo-walk-away",
    "people": 2,
    "line": "duo-walk-away | Walking Away Together | couple | walking, full body | scenes: beach, park, city, sunset, mountain | vibes: romantic, candid"
  },
  {
    "id": "duo-walk-toward",
    "people": 2,
    "line": "duo-walk-toward | Walking Toward | couple | walking, full body | scenes: city, beach, park, event, landmark | vibes: candid, casual"
  },
  {
    "id": "duo-twirl",
    "people": 2,
    "line": "duo-twirl | The Twirl | couple | standing, full body | scenes: beach, event, park, sunset, landmark | vibes: romantic, playful"
  },
  {
    "id": "duo-hug-front",
    "people": 2,
    "line": "duo-hug-front | Hug from Behind | couple | standing, half body | scenes: sunset, beach, mountain, water, park | vibes: romantic, candid"
  },
  {
    "id": "duo-bench",
    "people": 2,
    "line": "duo-bench | Bench Together | couple | sitting, full body | scenes: park, city, water, cafe, landmark | vibes: casual, romantic | needs a bench or ledge"
  },
  {
    "id": "duo-stairs",
    "people": 2,
    "line": "duo-stairs | Stair Duo | couple | sitting, full body | scenes: stairs, city, landmark | vibes: casual, confident | needs steps"
  },
  {
    "id": "duo-jump",
    "people": 2,
    "line": "duo-jump | Jump Together | couple | jumping, full body | scenes: beach, mountain, park, snow, sunset | vibes: playful, adventurous"
  },
  {
    "id": "duo-point-together",
    "people": 2,
    "line": "duo-point-together | Look Over There | couple | standing, full body | scenes: mountain, landmark, city, water | vibes: playful, adventurous"
  },
  {
    "id": "duo-shoulder-lean",
    "people": 2,
    "line": "duo-shoulder-lean | Shoulder Lean | couple | standing, half body | scenes: cafe, park, city, event, home | vibes: romantic, casual"
  },
  {
    "id": "duo-laugh-candid",
    "people": 2,
    "line": "duo-laugh-candid | Laughing Together | couple | standing, half body | scenes: cafe, event, park, beach, home, city | vibes: candid, playful"
  },
  {
    "id": "duo-power",
    "people": 2,
    "line": "duo-power | Power Duo | couple | standing, full body | scenes: city, office, event, gym, landmark | vibes: confident, professional"
  },
  {
    "id": "duo-heart-hands",
    "people": 2,
    "line": "duo-heart-hands | Heart Hands | couple | standing, half body | scenes: sunset, beach, event, landmark, park | vibes: romantic, playful"
  }
];
