import type { FigureSpec } from '../poseDsl';
import { arm, leg } from './builders';
import type { PoseDefinition } from './types';

type Partial2 = Omit<FigureSpec, 'at' | 'height'> & { at?: FigureSpec['at']; height?: number };

/** Two people side by side; `gap` is the distance between their hip centers (view widths). */
function pair(left: Partial2, right: Partial2, gap = 0.26, y = 0.48, height = 0.68): FigureSpec[] {
  return [
    { at: { x: 0.5 - gap / 2, y }, height, ...left },
    { at: { x: 0.5 + gap / 2, y }, height, ...right },
  ];
}

const HALF = { y: 0.8, height: 1.0 };

export const COUPLE_POSES: PoseDefinition[] = [
  {
    id: 'duo-hold-hands',
    name: 'Hand in Hand',
    people: 2,
    posture: 'standing',
    framing: 'full',
    scenes: ['beach', 'park', 'city', 'sunset', 'landmark', 'event'],
    vibes: ['romantic', 'casual'],
    cues: ['Stand side by side', 'Hold hands between you', 'Look at each other and laugh'],
    photoTip: 'Frame both fully with equal space on each side.',
    camera: 'eye',
    figures: pair(
      { armL: arm.relaxed('L'), armR: arm.holdHandLow('R'), legL: leg.straight('L'), legR: leg.straight('R'), head: 8, turn: 0.2 },
      { armL: arm.holdHandLow('L'), armR: arm.relaxed('R'), legL: leg.straight('L'), legR: leg.straight('R'), head: -8, turn: -0.2 },
      0.3,
    ),
  },
  {
    id: 'duo-side-hug',
    name: 'Side Hug',
    people: 2,
    posture: 'standing',
    framing: 'full',
    scenes: ['landmark', 'mountain', 'event', 'city', 'park', 'beach'],
    vibes: ['casual', 'romantic'],
    cues: ['Stand close, shoulders touching', 'Wrap your inner arms around each other', 'Both smile at the camera'],
    photoTip: 'Classic travel photo — keep the landmark between or above their heads.',
    camera: 'eye',
    figures: pair(
      { armL: arm.relaxed('L'), armR: arm.aroundPartner('R'), legL: leg.straight('L'), legR: leg.straight('R'), head: 6 },
      { armL: arm.aroundPartner('L'), armR: arm.relaxed('R'), legL: leg.straight('L'), legR: leg.straight('R'), head: -6 },
      0.2,
    ),
  },
  {
    id: 'duo-back-to-back',
    name: 'Back to Back',
    people: 2,
    posture: 'standing',
    framing: 'full',
    scenes: ['city', 'wall', 'park', 'event', 'gym'],
    vibes: ['confident', 'playful'],
    cues: ['Stand back to back', 'Cross your arms', 'Both turn your heads to the camera'],
    photoTip: 'Plain backgrounds make this one pop.',
    camera: 'eye',
    figures: pair(
      { turn: -0.6, armL: arm.acrossBody('L'), armR: arm.acrossBody('R'), legL: leg.straight('L'), legR: leg.straight('R') },
      { turn: 0.6, armL: arm.acrossBody('L'), armR: arm.acrossBody('R'), legL: leg.straight('L'), legR: leg.straight('R') },
      0.18,
    ),
  },
  {
    id: 'duo-forehead-touch',
    name: 'Forehead Touch',
    people: 2,
    posture: 'standing',
    framing: 'half',
    scenes: ['sunset', 'beach', 'park', 'event', 'water'],
    vibes: ['romantic', 'elegant'],
    cues: ['Face each other', 'Lean in until your foreheads touch', 'Close your eyes and smile'],
    photoTip: 'Shoot them in profile against the light.',
    camera: 'eye',
    figures: pair(
      { turn: 0.85, head: 12, armL: arm.relaxed('L'), armR: arm.holdHandLow('R'), legL: leg.straight('L'), legR: leg.straight('R') },
      { turn: -0.85, head: -12, armL: arm.holdHandLow('L'), armR: arm.relaxed('R'), legL: leg.straight('L'), legR: leg.straight('R') },
      0.28,
      HALF.y,
      HALF.height,
    ),
  },
  {
    id: 'duo-walk-away',
    name: 'Walking Away Together',
    people: 2,
    posture: 'walking',
    framing: 'full',
    scenes: ['beach', 'park', 'city', 'sunset', 'mountain'],
    vibes: ['romantic', 'candid'],
    cues: ['Hold hands', 'Walk slowly away from the camera', 'One of you look back over the shoulder'],
    photoTip: 'Stay still and use burst mode as they walk.',
    camera: 'eye',
    figures: pair(
      { facing: 'away', armL: arm.relaxed('L'), armR: arm.holdHandLow('R'), legL: leg.straight('L'), legR: leg.stepping('R') },
      { facing: 'away', head: -10, armL: arm.holdHandLow('L'), armR: arm.relaxed('R'), legL: leg.stepping('L'), legR: leg.straight('R') },
      0.22,
    ),
  },
  {
    id: 'duo-walk-toward',
    name: 'Walking Toward',
    people: 2,
    posture: 'walking',
    framing: 'full',
    scenes: ['city', 'beach', 'park', 'event', 'landmark'],
    vibes: ['candid', 'casual'],
    cues: ['Hold hands and walk toward the camera', 'Talk to each other', 'Do not look at the lens'],
    photoTip: 'Walk backwards slowly in front of them, or use burst mode.',
    camera: 'eye',
    figures: pair(
      { head: 10, armL: arm.relaxed('L'), armR: arm.holdHandLow('R'), legL: leg.straight('L'), legR: leg.stepping('R') },
      { head: -6, armL: arm.holdHandLow('L'), armR: arm.relaxed('R'), legL: leg.stepping('L'), legR: leg.straight('R') },
      0.22,
    ),
  },
  {
    id: 'duo-twirl',
    name: 'The Twirl',
    people: 2,
    posture: 'standing',
    framing: 'full',
    scenes: ['beach', 'event', 'park', 'sunset', 'landmark'],
    vibes: ['romantic', 'playful'],
    cues: ['One partner raises their hand', 'The other holds it and spins underneath', 'Laugh — movement makes the photo'],
    photoTip: 'Burst mode; dresses and scarves look great mid-spin.',
    camera: 'eye',
    figures: pair(
      { armL: arm.relaxed('L'), armR: arm.holdHandHigh('R'), legL: leg.straight('L'), legR: leg.straight('R'), turn: 0.3 },
      { armL: arm.holdHandHigh('L'), armR: arm.relaxed('R'), legL: leg.straight('L'), legR: leg.kneePop('R'), turn: -0.2 },
      0.24,
    ),
  },
  {
    id: 'duo-hug-front',
    name: 'Hug from Behind',
    people: 2,
    posture: 'standing',
    framing: 'half',
    scenes: ['sunset', 'beach', 'mountain', 'water', 'park'],
    vibes: ['romantic', 'candid'],
    cues: ['One stands in front', 'The partner behind wraps their arms around the waist', 'Lean heads together'],
    photoTip: 'The taller partner stands behind; slightly offset faces so both are visible.',
    camera: 'eye',
    figures: [
      { at: { x: 0.43, y: 0.84 }, height: 0.98, armL: arm.relaxed('L'), armR: arm.relaxed('R'), legL: leg.straight('L'), legR: leg.straight('R'), head: 8 },
      { at: { x: 0.58, y: 0.78 }, height: 1.02, armL: { upper: -30, lower: -80, lowerLen: 0.8 }, armR: arm.relaxed('R'), legL: leg.straight('L'), legR: leg.straight('R'), head: -10 },
    ],
  },
  {
    id: 'duo-bench',
    name: 'Bench Together',
    people: 2,
    posture: 'sitting',
    framing: 'full',
    needs: 'a bench or ledge',
    scenes: ['park', 'city', 'water', 'cafe', 'landmark'],
    vibes: ['casual', 'romantic'],
    cues: ['Sit close on the bench', 'Lean your heads toward each other', 'Hands on knees or holding hands'],
    photoTip: 'Shoot at their eye level, a few steps back.',
    camera: 'eye',
    figures: pair(
      { head: 10, armL: arm.onKnee('L'), armR: arm.holdHandLow('R'), legL: leg.seated('L'), legR: leg.seated('R') },
      { head: -10, armL: arm.holdHandLow('L'), armR: arm.onKnee('R'), legL: leg.seated('L'), legR: leg.seated('R') },
      0.24,
      0.6,
    ),
  },
  {
    id: 'duo-stairs',
    name: 'Stair Duo',
    people: 2,
    posture: 'sitting',
    framing: 'full',
    needs: 'steps',
    scenes: ['stairs', 'city', 'landmark'],
    vibes: ['casual', 'confident'],
    cues: ['One sits a step higher than the other', 'Elbows on knees', 'Both look at the camera'],
    photoTip: 'Center the staircase for leading lines.',
    camera: 'eye',
    figures: [
      { at: { x: 0.38, y: 0.68 }, height: 0.62, armL: arm.onKnee('L'), armR: arm.onKnee('R'), legL: leg.seatedKneeUp('L'), legR: leg.seatedKneeUp('R') },
      { at: { x: 0.62, y: 0.52 }, height: 0.62, armL: arm.onKnee('L'), armR: arm.onKnee('R'), legL: leg.seated('L'), legR: leg.seated('R') },
    ],
  },
  {
    id: 'duo-jump',
    name: 'Jump Together',
    people: 2,
    posture: 'jumping',
    framing: 'full',
    scenes: ['beach', 'mountain', 'park', 'snow', 'sunset'],
    vibes: ['playful', 'adventurous'],
    cues: ['Count to three together', 'Jump with your arms up', 'Hold hands if you can'],
    photoTip: 'Get very low and use burst mode.',
    camera: 'low',
    figures: pair(
      { armL: arm.wideV('L'), armR: arm.wideV('R'), legL: leg.jumpTuck('L'), legR: leg.jumpTuck('R') },
      { armL: arm.wideV('L'), armR: arm.wideV('R'), legL: leg.jumpTuck('L'), legR: leg.jumpTuck('R') },
      0.4,
      0.42,
      0.6,
    ),
  },
  {
    id: 'duo-point-together',
    name: 'Look Over There',
    people: 2,
    posture: 'standing',
    framing: 'full',
    scenes: ['mountain', 'landmark', 'city', 'water'],
    vibes: ['playful', 'adventurous'],
    cues: ['Stand close together', 'Both point at the same spot in the distance', 'Look where you are pointing'],
    photoTip: 'Leave empty space on the side they are pointing toward.',
    camera: 'eye',
    figures: pair(
      { turn: 0.3, armL: arm.relaxed('L'), armR: arm.point('R'), legL: leg.straight('L'), legR: leg.straight('R'), head: 10 },
      { turn: 0.3, armL: arm.relaxed('L'), armR: arm.point('R'), legL: leg.straight('L'), legR: leg.straight('R'), head: 10 },
      0.22,
    ),
  },
  {
    id: 'duo-shoulder-lean',
    name: 'Shoulder Lean',
    people: 2,
    posture: 'standing',
    framing: 'half',
    scenes: ['cafe', 'park', 'city', 'event', 'home'],
    vibes: ['romantic', 'casual'],
    cues: ['Stand side by side', 'One rests their head on the other’s shoulder', 'Soft smiles at the camera'],
    photoTip: 'Waist-up framing; focus on the eyes.',
    camera: 'eye',
    figures: pair(
      { head: 16, torso: 186, armL: arm.relaxed('L'), armR: arm.relaxed('R'), legL: leg.straight('L'), legR: leg.straight('R') },
      { armL: arm.relaxed('L'), armR: arm.relaxed('R'), legL: leg.straight('L'), legR: leg.straight('R'), head: -4 },
      0.24,
      HALF.y,
      HALF.height,
    ),
  },
  {
    id: 'duo-laugh-candid',
    name: 'Laughing Together',
    people: 2,
    posture: 'standing',
    framing: 'half',
    scenes: ['cafe', 'event', 'park', 'beach', 'home', 'city'],
    vibes: ['candid', 'playful'],
    cues: ['Turn toward each other', 'Tell a joke or share a memory', 'Laugh naturally — ignore the camera'],
    photoTip: 'Keep shooting through the laugh; the second laugh is usually the real one.',
    camera: 'eye',
    figures: pair(
      { turn: 0.45, head: 6, armL: arm.relaxed('L'), armR: arm.acrossBody('R'), legL: leg.straight('L'), legR: leg.straight('R') },
      { turn: -0.45, head: -10, armL: arm.toFace('L'), armR: arm.relaxed('R'), legL: leg.straight('L'), legR: leg.straight('R') },
      0.3,
      HALF.y,
      HALF.height,
    ),
  },
  {
    id: 'duo-power',
    name: 'Power Duo',
    people: 2,
    posture: 'standing',
    framing: 'full',
    scenes: ['city', 'office', 'event', 'gym', 'landmark'],
    vibes: ['confident', 'professional'],
    cues: ['Stand a little apart', 'Arms crossed or hands on hips', 'Serious look into the lens'],
    photoTip: 'Shoot from slightly below; keep both heads level in the frame.',
    camera: 'low',
    figures: pair(
      { turn: 0.25, armL: arm.acrossBody('L'), armR: arm.acrossBody('R'), legL: leg.wide('L'), legR: leg.wide('R') },
      { turn: -0.25, armL: arm.onHip('L'), armR: arm.onHip('R'), legL: leg.wide('L'), legR: leg.wide('R') },
      0.3,
    ),
  },
  {
    id: 'duo-heart-hands',
    name: 'Heart Hands',
    people: 2,
    posture: 'standing',
    framing: 'half',
    scenes: ['sunset', 'beach', 'event', 'landmark', 'park'],
    vibes: ['romantic', 'playful'],
    cues: ['Stand side by side', 'Each make half a heart with your inner hand', 'Join the halves between you'],
    photoTip: 'Place the sun or the landmark inside the heart.',
    camera: 'eye',
    figures: pair(
      { armL: arm.relaxed('L'), armR: { upper: 40, lower: 165, upperLen: 0.9 }, legL: leg.straight('L'), legR: leg.straight('R'), head: 6 },
      { armL: { upper: -40, lower: -165, upperLen: 0.9 }, armR: arm.relaxed('R'), legL: leg.straight('L'), legR: leg.straight('R'), head: -6 },
      0.42,
      HALF.y,
      HALF.height,
    ),
  },
];
