import { arm, figure, leg, SOLO_HALF, SOLO_SEATED } from './builders';
import type { PoseDefinition } from './types';

export const SOLO_POSES: PoseDefinition[] = [
  {
    id: 'solo-classic-hip',
    name: 'Hand on Hip',
    people: 1,
    posture: 'standing',
    framing: 'full',
    scenes: ['city', 'landmark', 'wall', 'event', 'park', 'office'],
    vibes: ['confident', 'elegant'],
    cues: ['Put one hand on your hip', 'Pop the opposite knee slightly', 'Chin a little down, shoulders relaxed'],
    photoTip: 'Shoot from chest height and leave a little space above the head.',
    camera: 'eye',
    figures: [figure({ armL: arm.onHip('L'), armR: arm.relaxed('R'), legL: leg.straight('L'), legR: leg.kneePop('R'), head: -4 })],
  },
  {
    id: 'solo-both-hips',
    name: 'Power Stance',
    people: 1,
    posture: 'standing',
    framing: 'full',
    scenes: ['city', 'mountain', 'landmark', 'office', 'gym'],
    vibes: ['confident', 'professional'],
    cues: ['Feet shoulder-width apart', 'Both hands on your hips', 'Stand tall and look straight at the lens'],
    photoTip: 'Crouch a little and shoot slightly upward to make the pose feel powerful.',
    camera: 'low',
    figures: [figure({ armL: arm.onHip('L'), armR: arm.onHip('R'), legL: leg.wide('L'), legR: leg.wide('R') })],
  },
  {
    id: 'solo-pockets',
    name: 'Hands in Pockets',
    people: 1,
    posture: 'standing',
    framing: 'full',
    scenes: ['city', 'cafe', 'night', 'wall', 'park'],
    vibes: ['casual', 'confident'],
    cues: ['Slide both hands into your pockets', 'Shift weight to one leg', 'Look slightly off-camera'],
    photoTip: 'Use a wide street or doorway behind them for depth.',
    camera: 'eye',
    figures: [figure({ armL: arm.inPocket('L'), armR: arm.inPocket('R'), legL: leg.straight('L'), legR: leg.kneePop('R'), turn: 0.15 })],
  },
  {
    id: 'solo-cross-legs',
    name: 'Crossed Ankles',
    people: 1,
    posture: 'standing',
    framing: 'full',
    scenes: ['city', 'cafe', 'wall', 'landmark', 'event'],
    vibes: ['elegant', 'casual'],
    cues: ['Cross one ankle over the other', 'One hand in a pocket, one relaxed', 'Tilt your head slightly'],
    photoTip: 'Frame from just above the head to below the feet; do not cut off the feet.',
    camera: 'eye',
    figures: [figure({ armL: arm.inPocket('L'), armR: arm.relaxed('R'), legL: leg.straight('L'), legR: leg.crossed('R'), head: 6 })],
  },
  {
    id: 'solo-wall-lean',
    name: 'Wall Lean',
    people: 1,
    posture: 'leaning',
    framing: 'full',
    needs: 'a wall or pillar',
    scenes: ['wall', 'city', 'night', 'cafe'],
    vibes: ['casual', 'confident'],
    cues: ['Lean one shoulder on the wall', 'Cross your ankles', 'Hands in pockets, look away and smile'],
    photoTip: 'Stand at an angle to the wall so its lines lead toward them.',
    camera: 'eye',
    figures: [figure({ torso: 172, armL: arm.inPocket('L'), armR: arm.inPocket('R'), legL: leg.straight('L'), legR: leg.crossed('R'), turn: 0.3 })],
  },
  {
    id: 'solo-wall-foot-up',
    name: 'Foot on the Wall',
    people: 1,
    posture: 'leaning',
    framing: 'full',
    needs: 'a wall',
    scenes: ['wall', 'city', 'night'],
    vibes: ['casual', 'confident'],
    cues: ['Lean your back on the wall', 'Bend one knee and rest that foot on the wall', 'Arms crossed or hands in pockets'],
    photoTip: 'Graffiti or textured walls work great; keep the wall parallel to the frame.',
    camera: 'eye',
    figures: [figure({ armL: arm.acrossBody('L'), armR: arm.acrossBody('R'), legL: leg.straight('L'), legR: leg.footUp('R') })],
  },
  {
    id: 'solo-arms-crossed',
    name: 'Arms Crossed',
    people: 1,
    posture: 'standing',
    framing: 'half',
    scenes: ['office', 'city', 'gym', 'event'],
    vibes: ['professional', 'confident'],
    cues: ['Cross your arms loosely', 'Relax your shoulders down', 'Give a small, confident smile'],
    photoTip: 'Waist-up framing; focus on the eyes and blur the background if you can.',
    camera: 'eye',
    figures: [figure({ ...SOLO_HALF, armL: arm.acrossBody('L'), armR: arm.acrossBody('R'), legL: leg.straight('L'), legR: leg.straight('R') })],
  },
  {
    id: 'solo-hair-touch',
    name: 'Hand in Hair',
    people: 1,
    posture: 'standing',
    framing: 'half',
    scenes: ['beach', 'sunset', 'park', 'cafe', 'water'],
    vibes: ['elegant', 'candid'],
    cues: ['Run one hand through your hair', 'Let the other arm hang relaxed', 'Look down, then slowly up'],
    photoTip: 'Shoot with the light behind or to the side for a soft glow.',
    camera: 'eye',
    figures: [figure({ ...SOLO_HALF, armL: arm.relaxed('L'), armR: arm.inHair('R'), legL: leg.straight('L'), legR: leg.straight('R'), head: 8, turn: 0.2 })],
  },
  {
    id: 'solo-thinker',
    name: 'Chin on Hand',
    people: 1,
    posture: 'standing',
    framing: 'half',
    scenes: ['cafe', 'office', 'home'],
    vibes: ['professional', 'candid'],
    cues: ['Cross one arm across your waist', 'Rest your chin lightly on the other hand', 'Look slightly past the camera'],
    photoTip: 'Use window light from the side; keep the background simple.',
    camera: 'eye',
    figures: [figure({ ...SOLO_HALF, armL: arm.acrossBody('L'), armR: arm.toFace('R'), legL: leg.straight('L'), legR: leg.straight('R'), head: -6 })],
  },
  {
    id: 'solo-wave',
    name: 'Hello Wave',
    people: 1,
    posture: 'standing',
    framing: 'full',
    scenes: ['beach', 'mountain', 'landmark', 'park', 'snow'],
    vibes: ['playful', 'casual'],
    cues: ['Raise one hand high and wave', 'Big smile', 'Other hand relaxed by your side'],
    photoTip: 'Step back so the landmark fills the frame behind them.',
    camera: 'eye',
    figures: [figure({ armL: arm.relaxed('L'), armR: arm.wave('R'), legL: leg.straight('L'), legR: leg.straight('R') })],
  },
  {
    id: 'solo-victory-v',
    name: 'Victory V',
    people: 1,
    posture: 'standing',
    framing: 'full',
    scenes: ['mountain', 'beach', 'sunset', 'landmark', 'snow'],
    vibes: ['adventurous', 'playful'],
    cues: ['Feet apart', 'Throw both arms up in a wide V', 'Chin up and celebrate'],
    photoTip: 'Get low and shoot upward so they stand against the sky.',
    camera: 'low',
    figures: [figure({ armL: arm.wideV('L'), armR: arm.wideV('R'), legL: leg.wide('L'), legR: leg.wide('R') })],
  },
  {
    id: 'solo-arms-wide',
    name: 'Arms Wide Open',
    people: 1,
    posture: 'standing',
    framing: 'full',
    scenes: ['mountain', 'beach', 'sunset', 'water', 'snow'],
    vibes: ['adventurous', 'candid'],
    cues: ['Stretch both arms out to the sides', 'Face the view, then turn your head to the camera', 'Breathe in and relax'],
    photoTip: 'Place them on the lower third with the horizon behind.',
    camera: 'eye',
    figures: [figure({ armL: arm.outstretched('L'), armR: arm.outstretched('R'), legL: leg.straight('L'), legR: leg.straight('R') })],
  },
  {
    id: 'solo-back-view-arms',
    name: 'Back to Camera',
    people: 1,
    posture: 'standing',
    framing: 'full',
    scenes: ['mountain', 'beach', 'sunset', 'water', 'landmark'],
    vibes: ['adventurous', 'candid'],
    cues: ['Turn your back to the camera', 'Face the view', 'Raise both arms wide'],
    photoTip: 'Keep the horizon straight and the person small enough to show the view.',
    camera: 'eye',
    figures: [figure({ facing: 'away', armL: arm.wideV('L'), armR: arm.wideV('R'), legL: leg.straight('L'), legR: leg.straight('R') })],
  },
  {
    id: 'solo-look-back',
    name: 'Over the Shoulder',
    people: 1,
    posture: 'standing',
    framing: 'full',
    scenes: ['city', 'landmark', 'beach', 'sunset', 'event'],
    vibes: ['elegant', 'candid'],
    cues: ['Turn your body away from the camera', 'Look back over your shoulder', 'Soft smile'],
    photoTip: 'Shoot from slightly behind and to the side.',
    camera: 'eye',
    figures: [figure({ facing: 'away', turn: -0.4, head: -10, armL: arm.relaxed('L'), armR: arm.relaxed('R'), legL: leg.straight('L'), legR: leg.kneePop('R') })],
  },
  {
    id: 'solo-walk-toward',
    name: 'Walking Toward',
    people: 1,
    posture: 'walking',
    framing: 'full',
    scenes: ['city', 'beach', 'park', 'stairs', 'landmark'],
    vibes: ['candid', 'casual'],
    cues: ['Walk slowly toward the camera', 'Swing your arms naturally', 'Look down or to the side, not at the lens'],
    photoTip: 'Use burst shots and stand in the middle of the path.',
    camera: 'eye',
    figures: [figure({ armL: arm.relaxed('L'), armR: flip15(arm.relaxed('R')), legL: leg.straight('L'), legR: leg.stepping('R'), head: 5 })],
  },
  {
    id: 'solo-profile',
    name: 'Side Profile',
    people: 1,
    posture: 'standing',
    framing: 'half',
    scenes: ['sunset', 'beach', 'water', 'mountain', 'city'],
    vibes: ['elegant', 'candid'],
    cues: ['Turn your body sideways', 'Look into the distance', 'Keep your chin parallel to the ground'],
    photoTip: 'Silhouette them against the bright sky for a dramatic look.',
    camera: 'eye',
    figures: [figure({ ...SOLO_HALF, turn: 0.85, armL: arm.relaxed('L'), armR: arm.relaxed('R'), legL: leg.straight('L'), legR: leg.straight('R') })],
  },
  {
    id: 'solo-head-tilt-smile',
    name: 'Head Tilt Smile',
    people: 1,
    posture: 'standing',
    framing: 'half',
    scenes: ['cafe', 'park', 'event', 'home', 'beach'],
    vibes: ['casual', 'playful'],
    cues: ['Turn your shoulders a little', 'Tilt your head to one side', 'Laugh, then smile'],
    photoTip: 'Ask them to laugh and shoot during the laugh.',
    camera: 'eye',
    figures: [figure({ ...SOLO_HALF, turn: 0.25, head: 12, armL: arm.relaxed('L'), armR: arm.relaxed('R'), legL: leg.straight('L'), legR: leg.straight('R') })],
  },
  {
    id: 'solo-hands-behind-head',
    name: 'Hands Behind Head',
    people: 1,
    posture: 'standing',
    framing: 'half',
    scenes: ['beach', 'park', 'mountain', 'gym'],
    vibes: ['casual', 'confident'],
    cues: ['Clasp your hands behind your head', 'Elbows wide', 'Close your eyes and enjoy the sun'],
    photoTip: 'Shoot slightly from below with the sky behind.',
    camera: 'low',
    figures: [figure({ ...SOLO_HALF, armL: arm.behindHead('L'), armR: arm.behindHead('R'), legL: leg.straight('L'), legR: leg.straight('R') })],
  },
  {
    id: 'solo-point-view',
    name: 'Point at the View',
    people: 1,
    posture: 'standing',
    framing: 'full',
    scenes: ['mountain', 'landmark', 'city', 'water'],
    vibes: ['adventurous', 'playful'],
    cues: ['Point at the landmark behind you', 'Turn halfway toward it', 'Look back at the camera with excitement'],
    photoTip: 'Line them up so the finger points at the main subject behind.',
    camera: 'eye',
    figures: [figure({ turn: 0.35, armL: arm.relaxed('L'), armR: arm.point('R'), legL: leg.straight('L'), legR: leg.straight('R') })],
  },
  {
    id: 'solo-jump',
    name: 'Jump Shot',
    people: 1,
    posture: 'jumping',
    framing: 'full',
    scenes: ['beach', 'mountain', 'park', 'snow', 'sunset'],
    vibes: ['playful', 'adventurous'],
    cues: ['Bend your knees', 'Jump with arms up', 'Tuck your legs at the top'],
    photoTip: 'Get very low and use burst mode; the best frame is at the peak.',
    camera: 'low',
    figures: [figure({ at: { x: 0.5, y: 0.42 }, armL: arm.wideV('L'), armR: arm.wideV('R'), legL: leg.jumpTuck('L'), legR: leg.jumpTuck('R') })],
  },
  {
    id: 'solo-sit-bench',
    name: 'Bench Sit',
    people: 1,
    posture: 'sitting',
    framing: 'full',
    needs: 'a bench, ledge or chair',
    scenes: ['park', 'city', 'cafe', 'water', 'landmark'],
    vibes: ['casual', 'candid'],
    cues: ['Sit near the edge, back straight', 'Hands resting on your knees', 'Look slightly away, then back'],
    photoTip: 'Shoot from their eye level, not from above.',
    camera: 'eye',
    figures: [figure({ ...SOLO_SEATED, armL: arm.onKnee('L'), armR: arm.onKnee('R'), legL: leg.seated('L'), legR: leg.seated('R') })],
  },
  {
    id: 'solo-sit-knee-up',
    name: 'Knee Up Sit',
    people: 1,
    posture: 'sitting',
    framing: 'full',
    needs: 'a step, rock or ledge',
    scenes: ['stairs', 'beach', 'mountain', 'park', 'water'],
    vibes: ['casual', 'adventurous'],
    cues: ['Sit down and pull one knee up', 'Rest your arm on that knee', 'Let the other leg relax'],
    photoTip: 'Lower the phone to their chest height and include the scenery.',
    camera: 'eye',
    figures: [figure({ ...SOLO_SEATED, armL: arm.relaxed('L'), armR: arm.onKnee('R'), legL: leg.seated('L'), legR: leg.seatedKneeUp('R'), head: 5 })],
  },
  {
    id: 'solo-sit-stairs',
    name: 'Stair Sit',
    people: 1,
    posture: 'sitting',
    framing: 'full',
    needs: 'steps',
    scenes: ['stairs', 'city', 'landmark'],
    vibes: ['casual', 'confident'],
    cues: ['Sit on a step with knees apart', 'Elbows on your knees', 'Lean slightly forward'],
    photoTip: 'Center the stairs so the lines lead to them.',
    camera: 'eye',
    figures: [figure({ ...SOLO_SEATED, torso: 180, armL: arm.onKnee('L'), armR: arm.onKnee('R'), legL: leg.seatedKneeUp('L'), legR: leg.seatedKneeUp('R') })],
  },
  {
    id: 'solo-sit-legs-out',
    name: 'Beach Lounge',
    people: 1,
    posture: 'sitting',
    framing: 'full',
    scenes: ['beach', 'park', 'water', 'sunset'],
    vibes: ['casual', 'candid'],
    cues: ['Sit on the ground', 'Stretch one leg out to the side', 'Lean back on one hand'],
    photoTip: 'Shoot low, close to the ground, with the horizon in the top third.',
    camera: 'low',
    figures: [
      figure({ at: { x: 0.38, y: 0.66 }, height: 0.66, torso: 168, armL: arm.relaxed('L'), armR: { upper: 30, lower: 30 }, legL: leg.seated('L'), legR: leg.seatedOut('R') }),
    ],
  },
  {
    id: 'solo-crouch',
    name: 'Street Crouch',
    people: 1,
    posture: 'crouching',
    framing: 'full',
    scenes: ['city', 'night', 'wall', 'stairs'],
    vibes: ['confident', 'casual'],
    cues: ['Crouch down with knees apart', 'Elbows resting on knees', 'Look straight at the lens'],
    photoTip: 'Get down to their eye level.',
    camera: 'low',
    figures: [figure({ at: { x: 0.5, y: 0.68 }, armL: arm.onKnee('L'), armR: arm.onKnee('R'), legL: leg.crouch('L'), legR: leg.crouch('R') })],
  },
  {
    id: 'solo-coffee',
    name: 'Coffee Moment',
    people: 1,
    posture: 'standing',
    framing: 'half',
    needs: 'a cup or drink',
    scenes: ['cafe', 'home', 'office'],
    vibes: ['candid', 'casual'],
    cues: ['Hold your cup with both hands near your chin', 'Look out the window', 'Soft smile'],
    photoTip: 'Focus on the face and keep the cup in the lower third.',
    camera: 'eye',
    figures: [figure({ ...SOLO_HALF, armL: arm.toFace('L'), armR: arm.toFace('R'), legL: leg.straight('L'), legR: leg.straight('R'), turn: 0.2 })],
  },
  {
    id: 'solo-railing',
    name: 'Railing Lean',
    people: 1,
    posture: 'leaning',
    framing: 'half',
    needs: 'a railing or balcony',
    scenes: ['water', 'city', 'mountain', 'landmark', 'night'],
    vibes: ['candid', 'elegant'],
    cues: ['Rest your elbow on the railing', 'Turn toward the camera', 'Relax the other hand'],
    photoTip: 'Keep the railing line diagonal for depth.',
    camera: 'eye',
    figures: [figure({ ...SOLO_HALF, at: { x: 0.42, y: SOLO_HALF.at.y }, torso: 175, armL: arm.relaxed('L'), armR: arm.restingHigh('R'), legL: leg.straight('L'), legR: leg.straight('R'), head: 6 })],
  },
  {
    id: 'solo-jacket-hold',
    name: 'Jacket Over Shoulder',
    people: 1,
    posture: 'standing',
    framing: 'full',
    scenes: ['city', 'event', 'night', 'office'],
    vibes: ['confident', 'elegant'],
    cues: ['Hook your jacket over one shoulder', 'Other hand in pocket', 'Look slightly away'],
    photoTip: 'Shoot from a little below eye level.',
    camera: 'low',
    figures: [figure({ armL: arm.inPocket('L'), armR: { upper: 165, lower: -10 }, legL: leg.straight('L'), legR: leg.kneePop('R'), turn: 0.2 })],
  },
  {
    id: 'solo-stairs-walk',
    name: 'Stair Climb',
    people: 1,
    posture: 'walking',
    framing: 'full',
    needs: 'steps',
    scenes: ['stairs', 'landmark', 'city'],
    vibes: ['candid', 'elegant'],
    cues: ['Walk up the stairs slowly', 'Look back toward the camera', 'Let one hand touch the railing'],
    photoTip: 'Stand at the bottom of the stairs and shoot upward.',
    camera: 'low',
    figures: [figure({ facing: 'away', head: -8, armL: arm.relaxed('L'), armR: arm.relaxed('R'), legL: leg.straight('L'), legR: { upper: 10, lower: -40, upperLen: 0.8 } })],
  },
  {
    id: 'solo-gym-flex',
    name: 'Flex',
    people: 1,
    posture: 'standing',
    framing: 'half',
    scenes: ['gym', 'beach'],
    vibes: ['confident', 'playful'],
    cues: ['Raise both arms to the side', 'Bend your elbows up', 'Flex and smile'],
    photoTip: 'Use side light to show definition.',
    camera: 'eye',
    figures: [figure({ ...SOLO_HALF, armL: { upper: -100, lower: 172, upperLen: 0.85 }, armR: { upper: 100, lower: -172, upperLen: 0.85 }, legL: leg.straight('L'), legR: leg.straight('R') })],
  },
  {
    id: 'solo-snow-sky',
    name: 'Reach for the Sky',
    people: 1,
    posture: 'standing',
    framing: 'full',
    scenes: ['snow', 'mountain', 'beach', 'park'],
    vibes: ['playful', 'adventurous'],
    cues: ['Stretch both arms straight up', 'Stand on your toes', 'Look up and smile'],
    photoTip: 'Shoot from low so the sky fills the background.',
    camera: 'low',
    figures: [figure({ armL: arm.straightUp('L'), armR: arm.straightUp('R'), legL: leg.straight('L'), legR: leg.straight('R') })],
  },
  {
    id: 'solo-portrait-straight',
    name: 'Classic Portrait',
    people: 1,
    posture: 'standing',
    framing: 'half',
    scenes: ['office', 'event', 'home', 'park', 'city'],
    vibes: ['professional', 'elegant'],
    cues: ['Turn your body slightly', 'Shoulders down and back', 'Face the camera, chin forward and down'],
    photoTip: 'Phone at eye level, focus on the eyes, background at least 2 m behind.',
    camera: 'eye',
    figures: [figure({ ...SOLO_HALF, turn: 0.3, armL: arm.relaxed('L'), armR: arm.relaxed('R'), legL: leg.straight('L'), legR: leg.straight('R') })],
  },
  {
    id: 'solo-landmark-small',
    name: 'Tiny in the View',
    people: 1,
    posture: 'standing',
    framing: 'full',
    scenes: ['mountain', 'landmark', 'water', 'snow', 'beach'],
    vibes: ['adventurous', 'candid'],
    cues: ['Stand on the left or right third', 'Face the view', 'Stay still — this shows the scale of the place'],
    photoTip: 'Step far back; the person should be about a quarter of the frame height.',
    camera: 'eye',
    figures: [figure({ at: { x: 0.33, y: 0.68 }, height: 0.28, facing: 'away', armL: arm.relaxed('L'), armR: arm.relaxed('R'), legL: leg.straight('L'), legR: leg.straight('R') })],
  },
];

/** Slightly swing an arm forward for a natural walking look. */
function flip15(limb: { upper: number; lower: number }) {
  return { ...limb, upper: limb.upper + 7, lower: limb.lower - 10 };
}
