/**
 * Writes supabase/functions/_shared/catalog.ts from the app's pose library so
 * the edge function can show Claude the poses it may choose from.
 * Run after editing poses: npm run gen:catalog
 */
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { catalogLine, POSES } from '../src/core/poses';

const entries = POSES.map((p) => ({ id: p.id, people: p.people, line: catalogLine(p) }));
const out = `// Generated by scripts/gen-catalog.ts — do not edit by hand.
export interface CatalogEntry {
  id: string;
  people: 1 | 2;
  line: string;
}

export const CATALOG: CatalogEntry[] = ${JSON.stringify(entries, null, 2)};
`;
writeFileSync(join(__dirname, '../supabase/functions/_shared/catalog.ts'), out);
console.log(`wrote ${entries.length} poses`);
